[project]
name = "whisper-api-fastapi"
version = "1.0.0"
description = "A FastAPI-based API for Whisper speech recognition using faster-whisper."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.3",
    "uvicorn[standard]",
    "uv",
    "faster-whisper>=1.2.1",
]
